## Now we are doing small operartions in numpy

## we are making small data structures  so that we do our operations in that data set only 

In [4]:
import numpy as np
import matplotlib.pyplot as plt 


In [5]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

In [8]:
print("zomato sales analysis")
print("sales data shape ",sales_data.shape) # here we are finding the rows and columns 
print("sample data for first three restraunt",sales_data[0,3])# ye hame zero row ka 3 column de rha hai jo ki 220000 hai lekin agar hame top se lekar 3rd restro ka poora data chahiye to ham aise likheeg 
print("sample data for first three restraunt",sales_data[0:3]) 




zomato sales analysis
sales data shape  (5, 5)
sample data for first three restraunt 220000
sample data for first three restraunt [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [18]:
# Total sales per year
sales_per_year=np.sum(sales_data,axis=0)
print(sales_per_year)


#yearly total
yearly_total=np.sum(sales_data[:, 1:],axis=0)
print(yearly_total)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
