#Hey this is my first notebook programming 
##lets start
--
going to do numpy programs

In [2]:
import numpy as np

##creating arrays from list 
--
##here we first create one dimensional array 
##then we create second dimenaional array

In [4]:
arr_1d=np.array([1,2,3,4,5])
print("1D Array:",arr_1d)

arr_2d=np.array([[1,2,3],[2,3,4]])
print("2d array:",arr_2d)

1D Array: [1 2 3 4 5]
2d array: [[1 2 3]
 [2 3 4]]


# comparison of list vs array

In [ ]:
#list multiplication
py_list=[1,2,3]
print("list multiplication:",py_list*2)

#array multiplication
np_arr=np.array([1,2,3])#here element wise multiplication occur
print("list multiplication:",np_arr*2)


#note-array me har ek element ke sath multiplication hota hai lekin list me har ek element double show honne lagta hai 

list multiplication: [1, 2, 3, 1, 2, 3]
list multiplication: [2 4 6]


# creating array from scratch 

In [15]:
#first we create an array whose all elements are zero
zeros=np.zeros((2,3))
print ("matrix of zeros:\n",zeros)

#now we create an array whose all elements are ones
ones=np.ones((2,3))
print ("matrix of ones:\n",ones)

#now we create an array whose all elements are any of the constant value with the help of full method 
full=np.full((2,3),8)
print ("matrix of constant value :\n",full)

#now we create an array whose all elements are any of the random value with the help of random class and random  method 
random=np.random.random((2,3))
print ("matrix of ones:\n",random)

matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
matrix of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
matrix of constant value :
 [[8 8 8]
 [8 8 8]]
matrix of ones:
 [[0.0983538  0.03184391 0.31392508]
 [0.064277   0.88628414 0.94813725]]


# creating vector ,matrix and tensor 

In [29]:
#vector
vector=np.array([1,2,3,4,5,6,])
print("vector:",vector)

#matrix
matrix=np.array([[1,2,3,4],[3,4,5,6]])
print("\nmatrix:\n",matrix)

#tensor
tensor=np.array([[[1,2],[3,4]],
                 [[4,5],[6,7]]])
print("\n tensor:/n",tensor)

vector: [1 2 3 4 5 6]

matrix:
 [[1 2 3 4]
 [3 4 5 6]]

 tensor:/n [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


## array properties 

In [31]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)  #gives rows and column
print("dimension:",arr.ndim)#gives dimension
print("size",arr.size)#size method gives us total number of elements in the array 
print("datatype",arr.dtype)#this method gives the datatype of the array

Shape: (2, 3)
dimension: 2
size 6
datatype int64


## reshaping the array 

In [36]:
arr=np.arange(12)
print("original array:",arr)

reshaped=arr.reshape(3,4)     #basically it reshaped the arr as per the given rows and columns
print("after rehshaping :",reshaped)

#if you want to do it again jaise pahle tha vaise then there is a method called flatten()
flattened=reshaped.flatten()
print("flattened array is",flattened)

#for transposed array
transposed=reshaped.T
print("transposed array is \n",transposed)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
after rehshaping : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array is [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array is 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
