# NUMPY array operations 

In [2]:
import numpy as np

# learning the concept of slicing in array numpy 

In [6]:
arr=np.array([1,2,3,4,5,6,6,7,8,9,10])
print(arr)
print("Basic slicing",arr[2:7])
print("with step",arr[1:7:2])
print("negative indexing",arr[-3])

[ 1  2  3  4  5  6  6  7  8  9 10]
Basic slicing [3 4 5 6 6]
with step [2 4 6]
negative indexing 8


# now we will learn how to do indexing and slicing in 2_D array

In [11]:
arr_2d=np.array([[2,3,4],
                 [4,5,8],
                 [6,7,8]])
#if we want element of 2 row of 2 column 
print("specific element",arr_2d[1,1])
print("specific row only without column",arr_2d[2])
print("specific column only",arr_2d[:,2])

specific element 5
specific row only without column [6 7 8]
specific column only [4 8 8]


# sorting
### sorting in 1d and 2d array both 

In [14]:
unsorted=np.array([0,2,3,62,1,2,4,5,36])
print("sorted array:",np.sort(unsorted))

#2d array
unsorted_2d=np.array([[1,2],[3,2],[6,5]])
#now there are two types of sorting in 2d array -: 1)row wise 2)column wise 

#first we will see column wise sorting
print("column wise sorting",np.sort(unsorted_2d,axis=0))    #axis =0 means column wise sorting  
print("row wise sorting",np.sort(unsorted_2d,axis=1))    #axis =0 means row wise sorting  
 

sorted array: [ 0  1  2  2  3  4  5 36 62]
column wise sorting [[1 2]
 [3 2]
 [6 5]]
row wise sorting [[1 2]
 [2 3]
 [5 6]]


# filtering

In [4]:
#numbers that gives you even number 0
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even=numbers[numbers%2==0]
print("even numbers",even)

even numbers [ 2  4  6  8 10]


# filter by mask 

In [16]:
mask= numbers>5
print("numbers greater thann 5 ",numbers[mask])

numbers greater thann 5  [ 6  7  8  9 10]


# fancy indexing vs where clause 

In [19]:
index=[1,2,3]# ye hamne list banaya hai jisme hamne 3 numbers paas kar diye hai aur ham log use as a index treat kar diye hai  
print(numbers[index]) # jo hamne number ke naam ka array banaya tha ham log usme se index ke hisab se elemnt ko print karwa rhe hai  

#now we are using where clause 
where_result=np.where(numbers>5)    #np.where() returns the indices (positions) where the condition is True.
print("numbers using where clause :",numbers[where_result])


[2 3 4]
numbers using where clause : [ 6  7  8  9 10]


# using where clause similarly as if else codition 

In [5]:
conditions_array=np.where(numbers>5,"True","False")
print(conditions_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## adding and deleting the array 

In [ ]:
# first we combine the two array with the help of concatenate method 
arr1=np.array([2,4,3])
arr2=np.array([7,8,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[2 3 4 6 7 8]


## adding new row and column in 2d array 

In [15]:
original=np.array([[1,2],[3,4]])
new_row=np.array([7,8])
with_new_row=np.vstack((original,new_row))# vstack is for adding new row in an array 
print("adding new row\n",with_new_row)

new_column=np.array([[7],[5]])
with_new_column=np.hstack((original,new_column))
print("addinf new column in array",with_new_column)

adding new row
 [[1 2]
 [3 4]
 [7 8]]
addinf new column in array [[1 2 7]
 [3 4 5]]
